<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite452d8b910eb6aac8fdea5c85141ab72
{
    public static $prefixLengthsPsr4 = array (
        's' => 
        array (
            'setasign\\Fpdi\\' => 14,
        ),
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'setasign\\Fpdi\\' => 
        array (
            0 => __DIR__ . '/..' . '/setasign/fpdi/src',
        ),
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'FPDF' => __DIR__ . '/..' . '/setasign/fpdf/fpdf.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInite452d8b910eb6aac8fdea5c85141ab72::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInite452d8b910eb6aac8fdea5c85141ab72::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInite452d8b910eb6aac8fdea5c85141ab72::$classMap;

        }, null, ClassLoader::class);
    }
}
